"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from kombo import utils



@dataclasses.dataclass
class PutCustomDatevEmployeesEmployeeIDPreparePayrollSuccessfulResponseData:
    pass

class PutCustomDatevEmployeesEmployeeIDPreparePayrollSuccessfulResponseStatus(str, Enum):
    SUCCESS = 'success'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class PutCustomDatevEmployeesEmployeeIDPreparePayrollSuccessfulResponse:
    data: PutCustomDatevEmployeesEmployeeIDPreparePayrollSuccessfulResponseData = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    status: PutCustomDatevEmployeesEmployeeIDPreparePayrollSuccessfulResponseStatus = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status') }})
    

