"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import getintegrationsintegrationidsuccessfulresponse as shared_getintegrationsintegrationidsuccessfulresponse
from typing import Optional


@dataclasses.dataclass
class GetIntegrationsIntegrationIDRequest:
    integration_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'integration_id', 'style': 'simple', 'explode': False }})
    r"""GET /integrations/:integration_id parameter"""
    



@dataclasses.dataclass
class GetIntegrationsIntegrationIDResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    get_integrations_integration_id_successful_response: Optional[shared_getintegrationsintegrationidsuccessfulresponse.GetIntegrationsIntegrationIDSuccessfulResponse] = dataclasses.field(default=None)
    r"""GET /integrations/:integration_id Successful response"""
    

