"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import gettoolscategoryparametercategory as shared_gettoolscategoryparametercategory
from ...models.shared import gettoolscategorysuccessfulresponse as shared_gettoolscategorysuccessfulresponse
from typing import Optional


@dataclasses.dataclass
class GetToolsCategoryRequest:
    category: shared_gettoolscategoryparametercategory.GetToolsCategoryParameterCategory = dataclasses.field(metadata={'path_param': { 'field_name': 'category', 'style': 'simple', 'explode': False }})
    r"""GET /tools/:category parameter"""
    



@dataclasses.dataclass
class GetToolsCategoryResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    get_tools_category_successful_response: Optional[shared_gettoolscategorysuccessfulresponse.GetToolsCategorySuccessfulResponse] = dataclasses.field(default=None)
    r"""GET /tools/:category Successful response"""
    

