"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import postcustomdatevpushdatageneralrequestbody as shared_postcustomdatevpushdatageneralrequestbody
from ...models.shared import postcustomdatevpushdatageneralsuccessfulresponse as shared_postcustomdatevpushdatageneralsuccessfulresponse
from typing import Optional


@dataclasses.dataclass
class PostCustomDatevPushDataGeneralRequest:
    x_integration_id: str = dataclasses.field(metadata={'header': { 'field_name': 'X-Integration-Id', 'style': 'simple', 'explode': False }})
    r"""ID of the integration you want to interact with."""
    post_custom_datev_push_data_general_request_body: Optional[shared_postcustomdatevpushdatageneralrequestbody.PostCustomDatevPushDataGeneralRequestBody] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""POST /custom/datev/push-data/general request body"""
    



@dataclasses.dataclass
class PostCustomDatevPushDataGeneralResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    post_custom_datev_push_data_general_successful_response: Optional[shared_postcustomdatevpushdatageneralsuccessfulresponse.PostCustomDatevPushDataGeneralSuccessfulResponse] = dataclasses.field(default=None)
    r"""POST /custom/datev/push-data/general Successful response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

