"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import dateutil.parser
import requests as requests_http
from ...models.shared import postcustomdatevpushdatapayrollsuccessfulresponse as shared_postcustomdatevpushdatapayrollsuccessfulresponse
from dataclasses_json import Undefined, dataclass_json
from datetime import datetime
from kombo import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PostCustomDatevPushDataPayrollRequestBody:
    r"""POST /custom/datev/push-data/payroll request body"""
    payroll_month: datetime = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('payroll_month'), 'encoder': utils.datetimeisoformat(False), 'decoder': dateutil.parser.isoparse }})
    r"""Specify the month for which the payroll data should be submitted. The date must be specified as the first day of a month (e.g. 2022-12-01).
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    



@dataclasses.dataclass
class PostCustomDatevPushDataPayrollRequest:
    x_integration_id: str = dataclasses.field(metadata={'header': { 'field_name': 'X-Integration-Id', 'style': 'simple', 'explode': False }})
    r"""ID of the integration you want to interact with."""
    request_body: Optional[PostCustomDatevPushDataPayrollRequestBody] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""POST /custom/datev/push-data/payroll request body"""
    



@dataclasses.dataclass
class PostCustomDatevPushDataPayrollResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    post_custom_datev_push_data_payroll_successful_response: Optional[shared_postcustomdatevpushdatapayrollsuccessfulresponse.PostCustomDatevPushDataPayrollSuccessfulResponse] = dataclasses.field(default=None)
    r"""POST /custom/datev/push-data/payroll Successful response"""
    

