"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import dateutil.parser
import requests as requests_http
from ...models.shared import putassessmentordersassessmentorderidresultsuccessfulresponse as shared_putassessmentordersassessmentorderidresultsuccessfulresponse
from dataclasses_json import Undefined, dataclass_json
from datetime import datetime
from enum import Enum
from kombo import utils
from typing import List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Attributes:
    field: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('field') }})
    value: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('value') }})
    


class Status(str, Enum):
    r"""Status of the assessment. Must be one of `COMPLETE` or `CANCELLED`."""
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'
    OPEN = 'OPEN'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PutAssessmentOrdersAssessmentOrderIDResultRequestBody:
    r"""PUT /assessment/orders/:assessment_order_id/result request body"""
    completed_at: datetime = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('completed_at'), 'encoder': utils.datetimeisoformat(False), 'decoder': dateutil.parser.isoparse }})
    r"""YYYY-MM-DDTHH:mm:ss.sssZ
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    result_url: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('result_url') }})
    status: Status = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status') }})
    r"""Status of the assessment. Must be one of `COMPLETE` or `CANCELLED`."""
    attributes: Optional[List[Attributes]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('attributes'), 'exclude': lambda f: f is None }})
    max_score: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('max_score'), 'exclude': lambda f: f is None }})
    score: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('score'), 'exclude': lambda f: f is None }})
    



@dataclasses.dataclass
class PutAssessmentOrdersAssessmentOrderIDResultRequest:
    assessment_order_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'assessment_order_id', 'style': 'simple', 'explode': False }})
    r"""PUT /assessment/orders/:assessment_order_id/result parameter"""
    x_integration_id: str = dataclasses.field(metadata={'header': { 'field_name': 'X-Integration-Id', 'style': 'simple', 'explode': False }})
    r"""ID of the integration you want to interact with."""
    request_body: Optional[PutAssessmentOrdersAssessmentOrderIDResultRequestBody] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""PUT /assessment/orders/:assessment_order_id/result request body"""
    



@dataclasses.dataclass
class PutAssessmentOrdersAssessmentOrderIDResultResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    put_assessment_orders_assessment_order_id_result_successful_response: Optional[shared_putassessmentordersassessmentorderidresultsuccessfulresponse.PutAssessmentOrdersAssessmentOrderIDResultSuccessfulResponse] = dataclasses.field(default=None)
    r"""PUT /assessment/orders/:assessment_order_id/result Successful response"""
    

