"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import dateutil.parser
import requests as requests_http
from ...models.shared import putcustomdatevemployeesemployeeidcompensationssuccessfulresponse as shared_putcustomdatevemployeesemployeeidcompensationssuccessfulresponse
from dataclasses_json import Undefined, dataclass_json
from datetime import datetime
from enum import Enum
from kombo import utils
from typing import List, Optional

class Currency(str, Enum):
    r"""The currency in which the employee gets paid. Currently, only euro is supported as integrated systems only work with Euro."""
    EUR = 'EUR'

class Period(str, Enum):
    r"""The period for which the specified amount is paid. Currently, integrated systems only support \\"HOUR\\" and \\"MONTH\\"."""
    HOUR = 'HOUR'
    MONTH = 'MONTH'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Compensations:
    amount: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('amount') }})
    r"""The amount that this employee will be paid."""
    currency: Currency = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('currency') }})
    r"""The currency in which the employee gets paid. Currently, only euro is supported as integrated systems only work with Euro."""
    period: Period = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('period') }})
    r"""The period for which the specified amount is paid. Currently, integrated systems only support \\"HOUR\\" and \\"MONTH\\"."""
    lohnart: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('lohnart'), 'exclude': lambda f: f is None }})
    r"""The Lohnart that should be used for this compensation. If not specified, the default Lohnart that was requested in the connection flow will be used. Generally Lohnart is only available for monthly compensations."""
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PutCustomDatevEmployeesEmployeeIDCompensationsRequestBody:
    r"""PUT /custom/datev/employees/:employee_id/compensations request body"""
    compensations: List[Compensations] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('compensations') }})
    effective_date: datetime = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('effective_date'), 'encoder': utils.datetimeisoformat(False), 'decoder': dateutil.parser.isoparse }})
    r"""Date from which the submitted compensations should be valid. Please note that it might not be possible to set compensations for the past if the payroll was already run.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    



@dataclasses.dataclass
class PutCustomDatevEmployeesEmployeeIDCompensationsRequest:
    x_integration_id: str = dataclasses.field(metadata={'header': { 'field_name': 'X-Integration-Id', 'style': 'simple', 'explode': False }})
    r"""ID of the integration you want to interact with."""
    employee_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'employee_id', 'style': 'simple', 'explode': False }})
    r"""ID of the employee that should be updated. You can use their Kombo `id` or their ID in the remote system by prefixing it with `remote:` (e.g., `remote:12312`)"""
    request_body: Optional[PutCustomDatevEmployeesEmployeeIDCompensationsRequestBody] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""PUT /custom/datev/employees/:employee_id/compensations request body"""
    



@dataclasses.dataclass
class PutCustomDatevEmployeesEmployeeIDCompensationsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    put_custom_datev_employees_employee_id_compensations_successful_response: Optional[shared_putcustomdatevemployeesemployeeidcompensationssuccessfulresponse.PutCustomDatevEmployeesEmployeeIDCompensationsSuccessfulResponse] = dataclasses.field(default=None)
    r"""PUT /custom/datev/employees/:employee_id/compensations Successful response"""
    

